import { Store } from './types';

export const storesData: Store[] = [
  {
    id: '1',
    name: 'max',
    logo: require('../../../../sources/images/max2.png'), 
    distance: '1.2km ',
    location:'secundrabad',
    status: 'Open now',
    isOpen: true,
  },
  {
    id: '2',
    name: 'adidas',
    logo: require('../../../../sources/images/adidas-logo.png'), 
    distance: '2.2km ',
    location:'secundrabad',
    status: 'Open now',
    isOpen: true,
  },
  {
    id: '3',
    name: 'puma',
    logo: require('../../../../sources/images/puma-logo.png'), 
    distance: '1.2km ',
    location:'secundrabad',
    status: 'Open now',
    isOpen: true,
  },
  {
    id: '4',
    name: 'zudio',
    logo: require('../../../../sources/images/zudio-logo.png'), 
    distance: '1.2km ',
    location:'secundrabad',
    status: 'Open now',
    isOpen: true,
  },
  {
    id: '5',
    name: 'Nike',
    logo: require('../../../../sources/images/lifestyle-logo.png'), 
    distance: '0.8km ',
    location:'secundrabad',
    status: 'Open now',
    isOpen: true,
  },
  {
    id: '6',
    name: 'H&M',
    logo: require('../../../../sources/images/westide-logo.png'),
    distance: '2.5km ',
    location:'secundrabad',
    status: 'Closes at 9 PM',
    isOpen: true,
  },
];
